name: Deploy to lambda
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Run a multi-line script
      run: |
        # Install PIP
        python -m pip install --upgrade pip
        # Install all dependencies as defined by requirements.txt in the current directory
        pip3 install -r requirements.txt -t .
        # For installing invidividual modules
        # Zip files into current directory
        zip -r gnomo-lambda.zip .

        # Ensuring current working directory is accessible by the function--this might not be doing anything
        export PATH=$PATH:$(pwd)
    - name: AWS Lambda Deploy
      uses: appleboy/lambda-action@master
      with:
        function_name: reportTenant
        zip_file: reportTenant.zip